In [4]:
import numpy as np

In [5]:
taxi = np.loadtxt('C:\\Users\\DELL\\Downloads\\nyc_taxis.csv', delimiter=',', skiprows=1)
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

# What is the mean speed of the cab rides?

In [7]:
speed = taxi[:, 7] /(taxi[:, 8]/3600)

In [8]:
speed

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

In [9]:
mean_speed = speed.mean()

In [10]:
print(mean_speed)

32.24258580925573


In [11]:
mean_speed = np.mean(speed)
print(mean_speed)

32.24258580925573


# Q2. Calculate number of rides taken in the month of february? 
# February is given by the 2 month columns

In [13]:
rides_feb = taxi[taxi[:, 1] == 2, 1]

In [14]:
rides_feb.shape

(13333,)

In [15]:
rides_feb.shape[0]

13333

# Q3. Calculate the number of rides with a tip greater than $50?

In [19]:
above_50_tip = taxi[taxi[:, -3] > 50, -3]

In [20]:
above_50_tip

array([ 52.8 ,  60.  ,  59.34,  80.  ,  70.  ,  60.  ,  55.  ,  65.  ,
        80.  ,  62.  , 100.  ,  58.  ,  62.  ,  75.7 ,  60.  ,  70.  ])

In [21]:
above_50_tip.shape[0]

16

# Q4. Calculate the number of rides where drop was JFK airport?

In [22]:
JFK_rides = taxi[taxi[:, 6] == 2, 6]

In [23]:
JFK_rides.shape

(11832,)

In [24]:
JFK_rides.shape[0]

11832

# Exploratory Data Analysis EDA

In [25]:
taxi.shape

(89560, 15)

In [26]:
taxi.ndim

2

In [27]:
taxi.size

1343400

In [28]:
taxi.shape[0] * taxi.shape[1]

1343400

# changing the datatypes of columns

In [30]:
taxi[:, 0:7].astype('int')

array([[2016,    1,    1, ...,    0,    2,    4],
       [2016,    1,    1, ...,    0,    2,    1],
       [2016,    1,    1, ...,    0,    2,    6],
       ...,
       [2016,    6,   30, ...,    5,    2,    4],
       [2016,    6,   30, ...,    5,    2,    6],
       [2016,    6,   30, ...,    5,    2,    0]])

In [31]:
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

# Q Q2. Calculate number of rides taken in the month of february

In [6]:
taxi[:, 1] == 2

array([False, False, False, ..., False, False, False])

In [9]:
taxi[taxi[:, 1] == 2, 1]

array([2., 2., 2., ..., 2., 2., 2.])

In [13]:
taxi[taxi[:, 1] == 2, 1]

array([2., 2., 2., ..., 2., 2., 2.])